export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "Snippet", icon: "code", color: "#6366f1", isSystem: true },
  { id: "type_prompt", name: "Prompt", icon: "sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_command", name: "Command", icon: "terminal", color: "#06b6d4", isSystem: true },
  { id: "type_note", name: "Note", icon: "file-text", color: "#f59e0b", isSystem: true },
  { id: "type_file", name: "File", icon: "file", color: "#10b981", isSystem: true },
  { id: "type_image", name: "Image", icon: "image", color: "#ec4899", isSystem: true },
  { id: "type_url", name: "URL", icon: "link", color: "#3b82f6", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    userId: "user_1",
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-06-10T10:00:00Z",
  },
  {
    id: "col_2",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    userId: "user_1",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
  },
  {
    id: "col_3",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    userId: "user_1",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-06-12T10:00:00Z",
  },
  {
    id: "col_4",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    userId: "user_1",
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-06-05T10:00:00Z",
  },
  {
    id: "col_5",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    userId: "user_1",
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    userId: "user_1",
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-06-11T10:00:00Z",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "text",
    content:
      "export function useAuth() {\n  const session = useSession();\n  return { user: session?.data?.user, isLoading: session.status === 'loading' };\n}",
    description: "Custom authentication hook for React applications",
    isFavorite: true,
    isPinned: true,
    language: "typescript",
    tags: ["react", "auth", "hooks"],
    typeId: "type_snippet",
    collectionId: "col_1",
    userId: "user_1",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-06-15T10:00:00Z",
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "text",
    content:
      "export async function fetchWithRetry(url: string, retries = 3) {\n  for (let i = 0; i < retries; i++) {\n    try {\n      const res = await fetch(url);\n      if (!res.ok) throw new Error(res.statusText);\n      return await res.json();\n    } catch (e) {\n      if (i === retries - 1) throw e;\n    }\n  }\n}",
    description: "Fetch wrapper with exponential backoff retry logic",
    isFavorite: false,
    isPinned: true,
    language: "typescript",
    tags: ["api", "error-handling", "fetch"],
    typeId: "type_snippet",
    collectionId: "col_1",
    userId: "user_1",
    createdAt: "2026-01-20T10:00:00Z",
    updatedAt: "2026-06-12T10:00:00Z",
  },
  {
    id: "item_3",
    title: "Git Stash with Message",
    contentType: "text",
    content: "git stash push -m 'your message here'",
    description: "Stash changes with a descriptive message",
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ["git", "stash"],
    typeId: "type_command",
    collectionId: "col_3",
    userId: "user_1",
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-06-10T10:00:00Z",
  },
  {
    id: "item_4",
    title: "Explain This Code",
    contentType: "text",
    content:
      "Explain the following code in plain English. Describe what it does, why it works, and any potential edge cases:\n\n```\n{code}\n```",
    description: "Prompt to explain unfamiliar code",
    isFavorite: true,
    isPinned: false,
    language: null,
    tags: ["ai", "explain", "debugging"],
    typeId: "type_prompt",
    collectionId: "col_6",
    userId: "user_1",
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-06-11T10:00:00Z",
  },
  {
    id: "item_5",
    title: "Python List Comprehension",
    contentType: "text",
    content: "squares = [x**2 for x in range(10) if x % 2 == 0]",
    description: "Filter and transform with list comprehension",
    isFavorite: false,
    isPinned: false,
    language: "python",
    tags: ["python", "comprehension"],
    typeId: "type_snippet",
    collectionId: "col_4",
    userId: "user_1",
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-06-05T10:00:00Z",
  },
  {
    id: "item_6",
    title: "Project README Template",
    contentType: "text",
    content:
      "# Project Name\n\n## Overview\n\n## Getting Started\n\n### Prerequisites\n\n### Installation\n\n## Usage\n\n## Contributing\n\n## License",
    description: "Starter template for project documentation",
    isFavorite: false,
    isPinned: false,
    language: "markdown",
    tags: ["docs", "template", "readme"],
    typeId: "type_note",
    collectionId: "col_2",
    userId: "user_1",
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-06-08T10:00:00Z",
  },
  {
    id: "item_7",
    title: "Write Unit Tests",
    contentType: "text",
    content:
      "Write comprehensive unit tests for the following function. Cover happy path, edge cases, and error states. Use vitest and @testing-library/react if it's a React component:\n\n```\n{code}\n```",
    description: "Prompt to generate unit tests for a function or component",
    isFavorite: false,
    isPinned: false,
    language: null,
    tags: ["ai", "testing", "vitest"],
    typeId: "type_prompt",
    collectionId: "col_6",
    userId: "user_1",
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-06-09T10:00:00Z",
  },
  {
    id: "item_8",
    title: "Docker Compose Dev Setup",
    contentType: "text",
    content:
      "services:\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_USER: dev\n      POSTGRES_PASSWORD: dev\n      POSTGRES_DB: devdb\n    ports:\n      - '5432:5432'",
    description: "Local Postgres dev environment via Docker Compose",
    isFavorite: false,
    isPinned: false,
    language: "yaml",
    tags: ["docker", "postgres", "devops"],
    typeId: "type_file",
    collectionId: "col_2",
    userId: "user_1",
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-05-30T10:00:00Z",
  },
];
